### ISSUE TITLE
Can not update plugin details

### ISSUE THREAD

**Issue by svenjungnickel** [pixelandtonic/craftcom#4] opened 2017-11-22 22:06 UTC
I tried to update the plugin details, uploaded a screenshot and changed the documentationand  changelog path. But after hitting the submit button the spinner loops a while and then I got the error message **Couldn't save plugin**

**Comment by janhenckens** [comment] 2017-11-23 11:51
Same issue here, although the changes I make & the screenshots I upload are being saved.

**Comment by brandonkelly** [comment] 2017-11-27 21:29
Not able to reproduce this, so I’m assuming it has been fixed. Let me know if either of you are still seeing it, though.

**Comment by svenjungnickel** [comment] 2017-11-28 05:26
@brandonkelly just tried to update the long description but got the same error message again. The issue obviously still exists.

**Comment by brandonkelly** [comment] 2017-11-28 05:53
@svenjungnickel Which plugin?

**Comment by svenjungnickel** [comment] 2017-11-28 07:12
It is the **Redactor Font Awesome** plugin. However I was able to update all the other details I mentioned already, including the icon.

I reckon this problem only occurs when certain fields are not filled.

**Comment by svenjungnickel** [comment] 2017-11-28 09:53
Just did some more tests. Its kinda of bizarre.
The error message comes up on mobile, chrome as well as safari. The changes are not displayed on mobile. But when I load it on the desktop version it shows me the changes I made mobile. I also can make changes on the desktop and it saves without an error.

**Comment by brandonkelly** [comment] 2017-11-28 13:11
Awesome thanks. Sounds like a UI bug, then.

**Comment by benjamindavid** [comment] 2017-11-30 11:45
It looks like the bug happens with browsers providing partial support for FormData. Fix upcoming!

**Comment by mildlygeeky** [comment] 2017-12-02 20:08
Per a discussion with Brandon this morning, I was still encountering this error today. Looks like the server is getting a 500 error, with a SQL syntax bug being reported on the ajax call.

**Comment by NathanHeffley** [comment] 2017-12-03 19:17
I am having this issue with my plugin, contact-form-drip. I can't update any information. No matter what I change (or if I don't change anything) I can't save my plugin info. If I can submit specific info to help you test this I'd be more than happy to help.

**Comment by brandonkelly** [comment] 2017-12-04 00:34
This should be fixed now.

**Closed by brandonkelly** 2017-12-04 00:34 UTC
Labels: bug
